### ISSUE TITLE
Bundle an install of `pytest` in with this `conda` environment

### ISSUE THREAD

**Issue by CodeGat** [ACCESS-NRI/payu-condaenv#21]
Currently we have to resort to `pip install`ing `pytest` before running our repro-ci tests, because we do not have an appropriate install of pytest with our conda environment. 
Add in `pytest>=8.0.0` to our environment.

**Comment by aidanheerdegen** [comment]
I could have sworn I made an issue like this already, but I can't find it. There were some other dependencies I thought we should install too in this mystery issue I appear not to have created. Hrm.
