### ISSUE TITLE
Install of nco required for ice post-processing

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/payu-condaenv#23]
Ice post-processing (concatenation) of daily ice data files requires installation of ~`cdo`~ [nco](https://nco.sourceforge.net/)

https://github.com/ACCESS-NRI/access-om2-configs/issues/16#issuecomment-1970482151

**Comment by anton-seaice** [comment]
Where is micromamba installed ?

**Comment by aidanheerdegen** [comment]
> Where is micromamba installed (on gadi) ?

In this case I don't think it is. The workflow creates the environment on the GitHub runner and uses `conda pack` to create a self-contained environment that is unpacked on `gadi`

https://github.com/ACCESS-NRI/payu-condaenv/blob/main/.github/workflows/deploy.yml#L31-L50

But @CodeGat would know more.

**Comment by anton-seaice** [comment]
I am actually not sure we need to make this change? We can just `module load nco` and it is provided by the system ?

**Comment by aidanheerdegen** [comment]
> I am actually not sure we need to make this change? We can just `module load nco` and it is provided by the system ?

Yes we *could*. We have to install other supporting software so to my mind it seems reasonable to include `nco` as well. 

Avoiding `module load` also makes the script less NCI specific in my mind. Potentially also testable outside an NCI environment .
