### ISSUE TITLE
Add GitHub command line client (gh)

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/payu-condaenv#25]
This environment should contain the GitHub command line client gh 

https://anaconda.org/conda-forge/gh

This will allow users to create repositories directly from the command line

https://docs.github.com/en/migrations/importing-source-code/using-the-command-line-to-import-source-code/adding-locally-hosted-code-to-github#adding-a-local-repository-to-github-with-github-cli

and meets a need we have to provide users with simple ways to push their cloned experiments to their own GitHub repositories without forking the original repo, e.g. https://github.com/access-nri/access-om2-configs

**Comment by jo-basevi** [comment]
I think `gh` is already in the payu conda env? 
``` 
$ module use /g/data/vk83/modules
$ module load payu/1.1
$ which gh
/g/data/vk83/apps/payu/1.1/bin/gh
```
In the conda env file on `main`:
https://github.com/ACCESS-NRI/payu-condaenv/blob/ebe7e9556f027f979ee16610d87a67f2eed01c8c/env.yml#L12
