### ISSUE TITLE
Create module infrastructure for utilising conda environment

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/payu-condaenv#4]
`conda` environments can be activate and deactivated using modules on NCI. 

An example of how this is done is the `hh5` `conda` environments:

```
/g/data/hh5/public/modules/conda/
```

This could be copied and adapted for use in `vk83`.

**Comment by ScottWales** [comment]
Nowdays with containerised environments the modules just set PATH. Wrapper scripts in $PREFIX/bin for each program in the conda environment then load the container and run that function.

**Comment by aidanheerdegen** [comment]
> Nowdays with containerised environments the modules just set PATH. Wrapper scripts in $PREFIX/bin for each program in the conda environment then load the container and run that function.

Something like Dale's stuff?

https://github.com/coecms/cms-conda-singularity/blob/main/modules/common_v3

Does containerisation overcome the restriction of environment modules on modifying the environment only through the module mechanisms? 

I'm wondering if that makes a container a better solution for deploying `spack`? Can a containerised environment do a `. share/spack/setup-env.sh` step?

**Comment by ScottWales** [comment]
Basically yeah - see `/g/data/access/ngm/modules/ants/1.1.0`/`/g/data/access/ngm/apps/ants/1.1.0`. Dale does some extra tricks there to do with his overlay stuff and to support mpi.

You can set a entry point script on the container which runs before any command where you can activate the conda environment or spack or whatever - here's my [spack container's](https://github.com/ScottWales/spack-environments/blob/master/containers/base/entrypoint.sh).

**Comment by aidanheerdegen** [comment]
Awesome, thanks.
